""" Constants to be used for utilities """
VERBOSE_FALSE = 0
VERBOSE_VERY_LOW = 0.5
VERBOSE_BASIC = 1
VERBOSE_TRUE = 2
VERBOSE_VERY_HIGH = 3

MQTT_BROKER_ADDRESS = "localhost"
MQTT_CLIENT_TYPE_LISTENER = "MQTT_CLIENT_TYPE_LISTENER"
MQTT_CLIENT_TYPE_PUBLISHER = "MQTT_CLIENT_TYPE_PUBLISHER"

TOPIC_GROUP_VISION = "NAO_TOPIC_GROUP_VISION/"
TOPIC_HUMAN_DETECTION = TOPIC_GROUP_VISION+"NAO_TOPIC_HUMAN_DETECTED"
TOPIC_HEAD_TRACKER = TOPIC_GROUP_VISION+"NAO_TOPIC_HEAD_TRACKER"
TOPIC_IMAGE = TOPIC_GROUP_VISION+"NAO_TOPIC_IMAGE"
TOPIC_OBJECT_DETECTION = TOPIC_GROUP_VISION+"NAO_TOPIC_OBJECT_DETECTION"
TOPIC_EMOTION_DETECTION = TOPIC_GROUP_VISION+"NAO_TOPIC_EMOTION_DETECTION"

TOPIC_GROUP_SOUND = "NAO_TOPIC_GROUP_SOUND/"
TOPIC_SPEECH = TOPIC_GROUP_SOUND+"NAO_TOPIC_SPEECH"
TOPIC_MICENERGY = TOPIC_GROUP_SOUND+"NAO_TOPIC_MICENERGY"

TOPIC_DISTANCE = "NAO_TOPIC_DISTANCE"
TOPIC_DIRECTIVE_TTS = "NAO_TOPIC_DIRECTIVE_TTS"
TOPIC_DIRECTIVE_SYSTEM = "NAO_TOPIC_DIRECTIVE_SYSTEM"
TOPIC_POSTURE = "NAO_TOPIC_POSTURE"
TOPIC_MOTION = "NAO_TOPIC_MOTION"
TOPIC_SOCIAL_INTERPR = "NAO_TOPIC_SOCIAL_INTERPR"
TOPIC_BEHAVIOR = "NAO_TOPIC_BEHAVIOR"

TOPIC_LEDS = "NAO_TOPIC_LEDS"

STRING_SEPARATOR = "<str_sep>"
STRING_SEPARATOR_INNER = "<str_sep_inner>"

NAO_SERVICE_SYSTEM = "ALSystem"
NAO_SERVICE_AUTONOMOUS_LIFE = "ALAutonomousLife"
NAO_SERVICE_TTS = "ALTextToSpeech"
NAO_SERVICE_MEMORY = "ALMemory"
NAO_SERVICE_FACEDETECTION = "ALFaceDetection"
NAO_SERVICE_SONAR = "ALSonar"
NAO_SERVICE_POSTURE = "ALRobotPosture"
NAO_SERVICE_AUDIO = "ALAudioDevice"
NAO_SERVICE_VIDEO = "ALVideoDevice"
NAO_SERVICE_ANIMATION_PLAYER = "ALAnimationPlayer"
NAO_SERVICE_BEHAVIOR_MANAGER = "ALBehaviorManager"
NAO_SERVICE_LEDS = "ALLeds"
NAO_SERVICE_BASICAWARENESS = "ALBasicAwareness"
NAO_SERVICE_MOTION = "ALMotion"
NAO_SERVICE_VISION_RECOGNITION = "ALVisionRecognition"

NAO_EVENT_FACEDETECTED = "FaceDetected"
NAO_EVENT_TRIGGER_LEARN_FACE = "LearnFaceEvent"
NAO_EVENT_PICTURE_DETECTED = "PictureDetected"



DIRECTIVE_SHUT_DOWN = "shut_down"
DIRECTIVE_SLEEP = "to_sleep"
DIRECTIVE_SAY = "say"
DIRECTIVE_REPLY_TO = "reply_to"
DIRECTIVE_GOTOPOSTURE = "go_to_posture"
DIRECTIVE_MOVEHEAD = "move_head"
DIRECTIVE_PLAYANIMATION = "play_animation"
DIRECTIVE_LED_CHANGE_COLOR = "change_led_color"
DIRECTIVE_LED_SET_COLOR = "set_led_color"
DIRECTIVE_LED_SET_THINKING = "set_led_thinking_color"

COLORS_BLUE = "blue"
COLORS_WHITE = "white"
COLORS_GREEN = "green"
COLORS_RED = "red"
COLORS_YELLOW = "yellow"

POSTURE_SIT = "Sit"
POSTURE_CROUCH = "Crouch"
POSTURE_LAYINGBACK = "LayingBack"
POSTURE_LAYINGBELLY = "LayingBelly"
POSTURE_STAND = "Stand"

NAO_DEFAULT_ANIMATIONS_PATHS = {
    "Hey_1": "animations/Stand/Gestures/Hey_1"
}

ADDITIONAL_BEHAVIORS_FOLDER = "" # TO DEFINE IF NEEDED TO USE ADDITIONAL BEHAVIORS UPLOADED ON THE ROBOT